version: "3.7"

services:
  myredis:
    image: redis

  myvotingapp:
    image: quimnadalsalle/votingapp
    build:
      dockerfile: Dockerfile
      context: ./src/votingapp
    ports:
      - 8080:80
    environment:
      REDIS: "myredis:6379"

  mytest:
    image: quimnadalsalle/votingapp-test
    build:
      context: ./test
    environment:
      VOTINGAPP_HOST: "myvotingapp"

  mynginx:
    image: nginx
    build:
      context: ./nginx
    
