version: "3.7"

services:
  myvotingapp:
    image: quimndalsalle/votingapp
    build:
      dockerfile: Dockerfile
      context: ./src/votingapp
    ports:
      - 5050:5050
    environment:
      REDIS: "myredis:6379"

  webserver:
    image: quimnadalsalle/nginx
    container_name: nginx-webserver
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"

  myredis:
    image: redis

  mytest:
    image: quimnadalsalle/votingapp-test
    build:
      dockerfile: Dockerfile
      context: ./test
    environment:
      VOTINGAPP_HOST: "myvotingapp"
