#La imagen de golang viene de debian
FROM golang 
#copio desde votingapp hasta la imagen
COPY . .

RUN go get github.com/gorilla/websocket && \
    go get github.com/labstack/echo

RUN go build -o ./build ./src/votingapp && \
    cp -r ./src/votingapp/ui ./build





